"""
Module 6 - Ad Compositor

Post-processes the generated video to make it look like a real advertisement.

Pipeline:
  1. Main video plays normally (person walking)
  2. Final N seconds: fade to brand card — brand name, tagline, product image
  3. Output is a single mp4 ready to share

The brand card is built from:
  - brand_name: parsed from the user's brief
  - tagline: generated by Ollama from the brief + profile
  - product_image: the uploaded product image (optional)
"""

import os
import time
import textwrap

import cv2
import numpy as np
import imageio
from PIL import Image, ImageDraw, ImageFont


# ---------------------------------------------------------------------------
# Font loader — falls back gracefully if custom fonts unavailable
# ---------------------------------------------------------------------------

def _load_fonts(frame_h: int):
    size_brand   = max(28, int(frame_h * 0.055))
    size_tagline = max(18, int(frame_h * 0.030))
    size_small   = max(14, int(frame_h * 0.022))

    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "C:/Windows/Fonts/arial.ttf",
    ]
    candidates_reg = [p.replace("Bold", "Regular").replace("-Bold", "") for p in candidates]

    def try_load(paths, size):
        for p in paths:
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                pass
        return ImageFont.load_default()

    return (
        try_load(candidates,     size_brand),
        try_load(candidates_reg, size_tagline),
        try_load(candidates_reg, size_small),
    )


# ---------------------------------------------------------------------------
# Brand card builder
# ---------------------------------------------------------------------------

def _build_brand_card(
    frame_w: int, frame_h: int,
    brand_name: str,
    tagline: str,
    product_img: Image.Image = None,
    bg_color: tuple = (245, 245, 245),
    accent_color: tuple = (30, 30, 30),
) -> np.ndarray:
    """
    Build a static brand card as an RGB numpy array (H×W×3).

    Layout:
      - Clean light background
      - Product image left-center (if provided)
      - Brand name large, right or center
      - Tagline smaller, below brand name
      - Thin accent line above brand name
    """
    card = Image.new("RGB", (frame_w, frame_h), bg_color)
    draw = ImageDraw.Draw(card)

    font_brand, font_tag, font_small = _load_fonts(frame_h)

    # --- Product image (left side) ---
    prod_x = int(frame_w * 0.05)
    if product_img is not None:
        # Cap product image to max 35% of frame width to leave room for text
        max_prod_w = int(frame_w * 0.35)
        prod_h = int(frame_h * 0.50)
        prod_w = int(prod_h * product_img.width / product_img.height)
        if prod_w > max_prod_w:
            prod_w = max_prod_w
            prod_h = int(prod_w * product_img.height / product_img.width)
        prod_resized = product_img.convert("RGBA").resize(
            (prod_w, prod_h), Image.LANCZOS
        )
        card.paste(
            prod_resized,
            (prod_x, (frame_h - prod_h) // 2),
            prod_resized
        )
        text_x = prod_x + prod_w + int(frame_w * 0.05)
    else:
        text_x = int(frame_w * 0.10)

    # --- Accent line ---
    line_y = int(frame_h * 0.38)
    line_w = int(frame_w * 0.30)
    draw.rectangle(
        [text_x, line_y, text_x + line_w, line_y + 3],
        fill=accent_color
    )

    # --- Brand name ---
    brand_y = line_y + 14
    draw.text((text_x, brand_y), brand_name.upper(), font=font_brand, fill=accent_color)

    # Get brand text height for positioning tagline below
    try:
        bbox = draw.textbbox((text_x, brand_y), brand_name.upper(), font=font_brand)
        brand_text_h = bbox[3] - bbox[1]
    except AttributeError:
        brand_text_h = int(frame_h * 0.065)

    # --- Tagline ---
    tag_y = brand_y + brand_text_h + int(frame_h * 0.025)
    wrapped = textwrap.fill(tagline, width=32)
    draw.text(
        (text_x, tag_y), wrapped,
        font=font_tag,
        fill=(80, 80, 80)
    )

    # --- Subtle bottom strip ---
    strip_h = int(frame_h * 0.012)
    draw.rectangle(
        [0, frame_h - strip_h, frame_w, frame_h],
        fill=accent_color
    )

    return np.array(card)


# ---------------------------------------------------------------------------
# Tagline generator
# ---------------------------------------------------------------------------

def generate_tagline(brief: str, profile: dict, brand_name: str) -> str:
    """
    Generate a short ad tagline using Ollama.
    Falls back to a generic tagline if Ollama is unavailable.
    """
    try:
        import ollama
        ethnicity = profile.get("ethnicity", "")
        age       = profile.get("age", "")
        prompt = (
            f"Write a single short advertising tagline (max 8 words) for "
            f"'{brand_name}'. The ad features a {ethnicity} woman in her {age}. "
            f"Brand brief: {brief}. "
            f"Reply with only the tagline, no quotes, no explanation."
        )
        resp = ollama.chat(
            model="phi3:mini",
            messages=[{"role": "user", "content": prompt}]
        )
        tagline = resp["message"]["content"].strip().strip('"').strip("'")
        # Keep it short
        if len(tagline) > 60:
            tagline = tagline[:57] + "..."
        return tagline
    except Exception:
        return f"Define your style."


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def apply_ad_overlay(
    video_path: str,
    brand_name: str,
    tagline: str,
    out_path: str,
    product_img: Image.Image = None,
    target_duration_sec: int = 15,
    fade_frames: int = 12,
) -> str:
    """
    Post-process the generated video to look like an advertisement.

    Loops the animation to fill the target duration, then appends
    a brand card with fade transition at the end.

    Ad structure:
      - Person walking (looped to fill target_duration minus card time)
      - Smooth fade (~0.5s)
      - Brand card (2.5s) — brand name, tagline, product image

    Args:
        video_path:           Path to animation video from motion.py
        brand_name:           Brand name to display on card
        tagline:              Ad tagline to display
        out_path:             Output path for final ad video
        product_img:          Optional PIL Image of the product
        target_duration_sec:  Total ad length in seconds (15, 30, or 60)
        fade_frames:          Frames for fade transition

    Returns:
        out_path
    """
    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 24.0
    w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # Read all frames from Wan2.1 output
    source_frames = []
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        source_frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    cap.release()

    if not source_frames:
        print("[compositor] No frames found — returning original.")
        return video_path

    # --- Build walking frames — forward loop with crossfade at join point ---
    card_duration_sec = 2.5
    fade_sec          = fade_frames / fps
    walk_duration_sec = max(
        len(source_frames) / fps,
        target_duration_sec - card_duration_sec - fade_sec
    )
    walk_frame_count = int(walk_duration_sec * fps)

    # Crossfade the end of the clip into the beginning for smooth looping
    crossfade_n = min(12, len(source_frames) // 4)
    blended_loop = []
    for i in range(crossfade_n):
        alpha = i / crossfade_n
        end_f   = source_frames[-(crossfade_n - i)].astype(float)
        start_f = source_frames[i].astype(float)
        blended = (end_f * (1 - alpha) + start_f * alpha).astype(np.uint8)
        blended_loop.append(blended)
    seamless_clip = source_frames + blended_loop

    walk_frames = []
    while len(walk_frames) < walk_frame_count:
        walk_frames.extend(seamless_clip)
    walk_frames = walk_frames[:walk_frame_count]

    # --- Sample background color from corners of last frame ---
    last = walk_frames[-1]
    corners = [last[0, 0], last[0, -1], last[-1, 0], last[-1, -1]]
    bg_color = tuple(int(v) for v in np.array(corners).mean(axis=0).astype(int))
    if sum(bg_color) < 300:
        bg_color = (245, 245, 245)

    # --- Build brand card ---
    card = _build_brand_card(
        w, h,
        brand_name=brand_name,
        tagline=tagline,
        product_img=product_img,
        bg_color=bg_color,
    )

    # --- Fade transition ---
    last_frame = walk_frames[-1].astype(float)
    card_float = card.astype(float)
    fade = []
    for i in range(fade_frames):
        alpha   = i / fade_frames
        blended = (last_frame * (1 - alpha) + card_float * alpha).astype(np.uint8)
        fade.append(blended)

    # --- Brand card hold ---
    hold = [card] * int(fps * card_duration_sec)

    # --- Write final video ---
    writer = imageio.get_writer(
        out_path, fps=fps, codec="libx264", pixelformat="yuv420p"
    )
    for f in walk_frames:
        writer.append_data(f)
    for f in fade:
        writer.append_data(f)
    for f in hold:
        writer.append_data(f)
    writer.close()

    actual_duration = (len(walk_frames) + len(fade) + len(hold)) / fps
    print(f"[compositor] Final ad: {actual_duration:.1f}s → {out_path}")
    return out_path